"""empty message

Revision ID: 21fe899e90ce
Revises: 161db3fa8822
Create Date: 2021-05-10 20:58:50.009706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fe899e90ce'
down_revision = '161db3fa8822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cli', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('cliente', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email_cli', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id_cli'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email_cli'),
    sa.UniqueConstraint('email_cli')
    )
    op.drop_table('follow')
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('follower_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('clientes')
    # ### end Alembic commands ###
